# Generated by Django 4.2.1 on 2023-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='img1',
            field=models.ImageField(default=1, upload_to='images', verbose_name='HomePage Image 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='img2',
            field=models.ImageField(default=1, upload_to='images', verbose_name='HomePage Image 2'),
            preserve_default=False,
        ),
    ]
