# Generated by Django 4.2.1 on 2023-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homepage_img1_homepage_img2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='HomePage Category Image')),
                ('title', models.CharField(max_length=50, verbose_name='HomePage Category Title')),
            ],
            options={
                'verbose_name': 'Home Page Category',
                'verbose_name_plural': 'Home Page Categories',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=80, verbose_name='Titles Title 1')),
                ('colored_title1', models.CharField(max_length=50, verbose_name='Titles Colored Title 1')),
                ('title2', models.CharField(max_length=80, verbose_name='Titles Title 2')),
                ('colored_title2', models.CharField(max_length=50, verbose_name='Titles Colored Title 2')),
            ],
        ),
    ]
