# Generated by Django 4.2.1 on 2023-05-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_homepagecollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourNft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Your Nft Title')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Your Nft Button Name')),
            ],
        ),
        migrations.CreateModel(
            name='YourNftContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Your Nft Image')),
                ('title', models.CharField(max_length=50, verbose_name='Your Nft Title')),
                ('text', models.TextField(verbose_name='Your Nft Text')),
            ],
        ),
    ]
