# Generated by Django 4.2.1 on 2023-05-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_yournft_yournftcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='colored_title3',
            field=models.CharField(default=11, max_length=50, verbose_name='Titles Colored Title 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='title3',
            field=models.CharField(default=1, max_length=80, verbose_name='Titles Title 3'),
            preserve_default=False,
        ),
    ]
