# Generated by Django 4.2.1 on 2023-05-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_homeitemspath'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeItemsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Home Item Content Code')),
                ('img1', models.ImageField(upload_to='images', verbose_name='Home Item Content Image 1')),
                ('title', models.CharField(max_length=50, verbose_name='Home Item Content Title')),
                ('img2', models.ImageField(upload_to='images', verbose_name='Home Item Content Image 2')),
                ('name', models.CharField(max_length=50, verbose_name='Home Item Content Name')),
                ('name_link', models.CharField(max_length=50, verbose_name='Home Item Content Name Link')),
                ('subtitle1', models.CharField(max_length=30, verbose_name='Home Item Content Subtitle 1')),
                ('current_bid', models.CharField(max_length=40, verbose_name='Home Item Content Current Bid')),
                ('bid_price', models.FloatField(verbose_name='Home Item Content Bid Price')),
                ('subtitle2', models.CharField(max_length=30, verbose_name='Home Item Content Subtitle 2')),
                ('last_bid', models.CharField(max_length=50, verbose_name='Home Item Content Last Bid')),
                ('date', models.CharField(max_length=50, verbose_name='Home Item Content Date')),
                ('btn_name', models.CharField(max_length=50, verbose_name='Home Item Content Button Name')),
            ],
        ),
    ]
