# Generated by Django 4.2.1 on 2023-05-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_homeitemscontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeitemscontent',
            name='bid_price',
            field=models.CharField(max_length=50, verbose_name='Home Item Content Bid Price'),
        ),
    ]
