# Generated by Django 4.2.1 on 2023-05-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50, verbose_name='General Title 1')),
                ('subtitle1', models.CharField(max_length=80, verbose_name='General Title Subtitle 1')),
                ('page_name1', models.CharField(max_length=50, verbose_name='General Title Page Name 1')),
                ('title2', models.CharField(max_length=50, verbose_name='General Title 2')),
                ('subtitle2', models.CharField(max_length=80, verbose_name='General Title Subtitle 2')),
                ('page_name2', models.CharField(max_length=50, verbose_name='General Title Page Name 2')),
                ('title3', models.CharField(max_length=50, verbose_name='General Title 3')),
                ('subtitle3', models.CharField(max_length=80, verbose_name='General Title Subtitle 3')),
                ('page_name3', models.CharField(max_length=50, verbose_name='General Title Page Name 3')),
                ('title4', models.CharField(max_length=50, verbose_name='General Title 4')),
                ('subtitle4', models.CharField(max_length=80, verbose_name='General Title Subtitle 4')),
                ('page_name4', models.CharField(max_length=50, verbose_name='General Title Page Name 4')),
                ('btn_name1', models.CharField(max_length=50, verbose_name='General Title Button Name 1')),
                ('btn_name2', models.CharField(max_length=50, verbose_name='General Title Button Name 2')),
            ],
        ),
    ]
