# Generated by Django 4.2.1 on 2023-05-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_generaltitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='colored_title4',
            field=models.CharField(default=1, max_length=50, verbose_name='Titles Colored Title 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='colored_title5',
            field=models.CharField(default=1, max_length=50, verbose_name='Titles Colored Title 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='colored_title6',
            field=models.CharField(default=1, max_length=50, verbose_name='Titles Colored Title 6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='colored_title7',
            field=models.CharField(default=1, max_length=50, verbose_name='Titles Colored Title 7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='colored_title8',
            field=models.CharField(default=1, max_length=50, verbose_name='Titles Colored Title 8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='title4',
            field=models.CharField(default=1, max_length=80, verbose_name='Titles Title 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='title5',
            field=models.CharField(default=1, max_length=80, verbose_name='Titles Title 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='title6',
            field=models.CharField(default=1, max_length=80, verbose_name='Titles Title 6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='title7',
            field=models.CharField(default=1, max_length=80, verbose_name='Titles Title 7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='title8',
            field=models.CharField(default=1, max_length=80, verbose_name='Titles Title 8'),
            preserve_default=False,
        ),
    ]
