# Generated by Django 4.2.1 on 2023-05-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_createget_createpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='user_img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='User Image'),
            preserve_default=False,
        ),
    ]
