# Generated by Django 4.2.1 on 2023-05-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_createpost_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='user_img',
        ),
    ]
