# Generated by Django 4.2.1 on 2023-05-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_createpost_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Create Preview')),
                ('title', models.CharField(max_length=80, verbose_name='Create Preview Title')),
                ('profile_img', models.ImageField(upload_to='images', verbose_name='Create Preview Image')),
                ('name', models.CharField(max_length=50, verbose_name='Create Preview Name')),
                ('name_link', models.CharField(max_length=50, verbose_name='Create Preview Name Link')),
                ('text', models.TextField(verbose_name='Create Preview Text')),
            ],
        ),
        migrations.CreateModel(
            name='CreatePreviewContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Create Preview Content Title')),
                ('info1', models.CharField(max_length=50, verbose_name='Create Preview Content Info 1')),
                ('info2', models.CharField(max_length=50, verbose_name='Create Preview Content Info 2')),
            ],
        ),
    ]
