# Generated by Django 4.2.1 on 2023-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_createpreview_createpreviewcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_link', models.CharField(max_length=50, verbose_name='Name Link')),
                ('like', models.CharField(max_length=50, verbose_name='Like')),
                ('hand', models.CharField(max_length=50, verbose_name='Hand')),
                ('dollar', models.CharField(max_length=50, verbose_name='Dollar')),
                ('like_count1', models.PositiveIntegerField(verbose_name='Likes Count 1')),
                ('like_count2', models.PositiveIntegerField(verbose_name='Likes Count 2')),
                ('like_count3', models.PositiveIntegerField(verbose_name='Likes Count 3')),
                ('followers', models.CharField(max_length=60, verbose_name='Followers')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
        ),
    ]
