# Generated by Django 4.2.1 on 2023-05-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_authorpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='images', verbose_name='Profile Image')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle1', models.CharField(max_length=50, verbose_name='Subtitle 1')),
                ('subtitle2', models.CharField(max_length=50, verbose_name='Subtitle 2')),
                ('info1', models.CharField(max_length=50, verbose_name='Info 1')),
                ('info2', models.CharField(max_length=50, verbose_name='Info 2')),
                ('btn_name', models.CharField(max_length=50, verbose_name='Button Name')),
            ],
        ),
    ]
