# Generated by Django 4.2.1 on 2023-05-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_authorcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreTopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('inheritence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_items', to='main.homeitemscontent')),
            ],
        ),
    ]
