# Generated by Django 4.2.1 on 2023-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_exploretopitem_inheritence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreFirstItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_name1', models.CharField(max_length=40, verbose_name='Button Name 1')),
                ('profile_img1', models.ImageField(upload_to='images', verbose_name='Profile Image 1')),
                ('img1', models.ImageField(upload_to='images', verbose_name='Image 1')),
                ('title1', models.CharField(max_length=50, verbose_name='Title 1')),
                ('profile_img2', models.ImageField(upload_to='images', verbose_name='Profile Image 2')),
                ('img2', models.ImageField(upload_to='images', verbose_name='Image 2')),
                ('title2', models.CharField(max_length=50, verbose_name='Title 2')),
                ('subtitle1', models.CharField(max_length=50, verbose_name='Subtitle 1')),
                ('subtitle2', models.CharField(max_length=50, verbose_name='Subtitle 2')),
                ('subtitle3', models.CharField(max_length=50, verbose_name='Subtitle 3')),
                ('subtitle4', models.CharField(max_length=50, verbose_name='Subtitle 4')),
                ('info1', models.CharField(max_length=40, verbose_name='Info 1')),
                ('info2', models.CharField(max_length=40, verbose_name='Info 2')),
                ('info3', models.CharField(max_length=40, verbose_name='Info 3')),
                ('info4', models.CharField(max_length=40, verbose_name='Info 4')),
                ('btn_name2', models.CharField(max_length=40, verbose_name='Button Name 2')),
            ],
            options={
                'verbose_name': 'ExploreFirstItem',
                'verbose_name_plural': 'ExploreFirstItem',
            },
        ),
    ]
