# Generated by Django 4.2.1 on 2023-05-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_exploreitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='title9',
            field=models.CharField(default=1, max_length=80, verbose_name='Titles Title 1'),
            preserve_default=False,
        ),
    ]
