# Generated by Django 4.2.1 on 2023-05-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_title_title9'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=80, verbose_name='Subtitle')),
            ],
        ),
    ]
