# Generated by Django 4.2.1 on 2023-05-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_topseller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopSeller',
            new_name='ExploreTopSeller',
        ),
    ]
