# Generated by Django 4.2.1 on 2023-05-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_topseller_exploretopseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeitemscontent',
            name='bit_title',
            field=models.CharField(default=1, max_length=50, verbose_name='Bit Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeitemscontent',
            name='btn_name2',
            field=models.CharField(default=1, max_length=50, verbose_name='Button Name 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeitemscontent',
            name='info1',
            field=models.CharField(default=1, max_length=50, verbose_name='Info 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeitemscontent',
            name='info2',
            field=models.CharField(default=1, max_length=50, verbose_name='Info 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeitemscontent',
            name='subtitle3',
            field=models.CharField(default=1, max_length=30, verbose_name='Home Item Content Subtitle 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeitemscontent',
            name='text',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
