# Generated by Django 4.2.1 on 2023-05-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_homeitemscontent_img3'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=30, verbose_name='Home Item Content Subtitle 3')),
                ('bit_title', models.CharField(max_length=50, verbose_name='Bit Title')),
                ('btn_name1', models.CharField(max_length=50, verbose_name='Button Name 1')),
                ('btn_name2', models.CharField(max_length=50, verbose_name='Button Name 2')),
            ],
        ),
        migrations.RemoveField(
            model_name='homeitemscontent',
            name='bit_title',
        ),
        migrations.RemoveField(
            model_name='homeitemscontent',
            name='btn_name2',
        ),
        migrations.RemoveField(
            model_name='homeitemscontent',
            name='subtitle3',
        ),
    ]
