# Generated by Django 4.2.1 on 2023-05-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_detailinfo_remove_homeitemscontent_bit_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_link', models.CharField(max_length=50, verbose_name='Name Link')),
                ('bid', models.CharField(max_length=50, verbose_name='Bid')),
                ('datetime', models.CharField(max_length=50, verbose_name='Datetime')),
            ],
        ),
    ]
