# Generated by Django 4.2.1 on 2023-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_detailcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltitle',
            name='page_name5',
            field=models.CharField(default=1, max_length=50, verbose_name='General Title Page Name 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaltitle',
            name='subtitle5',
            field=models.CharField(default=1, max_length=80, verbose_name='General Title Subtitle 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaltitle',
            name='title5',
            field=models.CharField(default=1, max_length=50, verbose_name='General Title 5'),
            preserve_default=False,
        ),
    ]
